build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.20"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.20"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.20"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.20"
  i386: "ghcr.io/home-assistant/i386-base-python:3.12-alpine3.20"
labels:
  org.opencontainers.image.title: "ADS-B Dashboard"
  org.opencontainers.image.description: "HomeAssistant add-on for ADS-B receiver integration with tar1090"
  org.opencontainers.image.source: "https://github.com/mtebusi/ha-addons"
  org.opencontainers.image.licenses: "MIT"
args:
  PYTHON_VERSION: "3.12"
